### ISSUE TITLE
Not possible to output just modifier keys

### ISSUE THREAD

**Issue by JorWat25** [EPLHREU/emily-modifiers#2]
For example, in Windows, pressing the Windows key on its own opens up the Start Menu. I would assume that `-PLTZ` would output just the Windows Key, but it doesn't output anything with the dictionary (Plover will output '.S', as it interprets it as a pluralized period). Other key combos, like CTRL+Shift to change keyboard layouts, are similarly not possible (should be `-FRLTZ`).

**Comment by EPLHREU** [comment]
The latest commit (4e69df3) should now have fixed this, as I don't have a windows host to test with would you be able to provide feedback on if it works as expected? 

thanks! :)

**Comment by JorWat25** [comment]
Yep, works great now! Thanks for the quick work.

**Comment by EPLHREU** [comment]
I'm glad!
good catch on it, something I didn't consider :D
