### ISSUE TITLE
Adding apple/command modifier key

### ISSUE THREAD

**Issue by willcohen** [EPLHREU/emily-modifiers#6]
For Mac users who want to chord out commands, it’d be lovely to have a way to include the apple/command key as one of these modifiers. Currently I think a lot of Mac users just have control redirect to command during steno, but for any Mac users that also use control (ie emacs), both control and command get regularly used.

My initial thought is that perhaps a two-key chord within FRPB could be overloaded to send the Apple command key instead of one of the existing four modifiers? My initial inclination is that PB might be best, so that F and R can still reach the * without needing to chord FR too.

If this seems reasonable, I’d be happy to draft up a PR!

**Comment by willcohen** [comment]
Apologies. Brain freeze. I’d had so many keyboard modifiers going that super wasn’t working when it should have. Closing.

**Comment by EPLHREU** [comment]
No worries, glad you found that out! 
Thanks for the willingness to help and come forward with stuff though :)
